---
- hosts: all
  tasks:
  - name: sleep using a passed in value to test async
    async: 5
    poll: 0
    ansible.builtin.command:
      cmd: sleep {{ time_to_sleep }} && echo awake
    register: sleeper

  - name: debug
    ansible.builtin.debug:
      msg: "Hello World from {{ inventory_hostname }}"

  - name: Wait for asynchronous job to end
    ansible.builtin.async_status:
      jid: '{{ sleeper.ansible_job_id }}'
    register: job_result
    until: job_result.finished
    retries: 10
    delay: 5

  - name: debug sleeper
    ansible.builtin.debug:
      var: sleeper 

