---
- hosts: all
  tasks:
  - name: sleep using a passed in value to test async
    async: 5
    poll: 0
    ansible.builtin.command:
      cmd: sleep {{ time_to_sleep }} && echo awake
    register: output

  - name: debug
    ansible.builtin.debug:
      msg: "Hello World from {{ inventory_hostname }}"

  - name: Check sync status
  async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  loop: "{{ async_results.results }}"
  loop_control:
    loop_var: "async_result_item"
  register: async_poll_results
  until: async_poll_results.finished
  retries: 30

  - name: debug
    ansible.builtin.debug:
      var: output 

