---
- hosts: all
  tasks:
  - name: sleep using a passed in value to test async
    async: 5
    poll: 0
    ansible.builtin.command:
      cmd: sleep {{ time_to_sleep }}
  - name: debug
    ansible.builtin.debug:
      msg: "Hello World from {{ inventory_hostname }}"

